title: "How Do I win a Pickleball Point"
description: "Predicting the winner of a pickleball point through Machine Learning"
baseurl: "" # if hosting at root of GitHub pages
url: "https://calebhyun.github.io" # your GitHub Pages URL

markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-toc
  - jekyll-seo-tag
